services:
  ollama:
    image: ollama/ollama:0.4.5
    ports:
      - 19269:11434
    environment:
      - OLLAMA_KEEP_ALIVE=-1
    tty: true
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
      - ./modelfiles:/modelfiles
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]

volumes:
  ollama_data:
    driver: local
